CREATE DATABASE QLCUAHANG
GO

USE QLCUAHANG
GO

CREATE TABLE NHAN_VIEN (
	ma_nv VARCHAR(10) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
	ten_nv NVARCHAR(50) NOT NULL,
	dchi_nv NVARCHAR(255) NOT NULL,
	gtinh_nv NVARCHAR(10) NOT NULL,
	sdt_nv VARCHAR(10) CHECK (LEN(sdt_nv) = 10),
	tthai_nv BIT DEFAULT 1
);
GO

CREATE TABLE TAI_KHOAN (
	tkhoan VARCHAR(50) CONSTRAINT PK_TAIKHOAN PRIMARY KEY,
	mkhau VARCHAR(25) NOT NULL,
	tthai_tk BIT DEFAULT 1,
	ma_nv VARCHAR(10) CONSTRAINT FR_TKNV
		FOREIGN KEY REFERENCES NHAN_VIEN(ma_nv)
);
GO

CREATE TABLE KHACH_HANG (
	sdt_kh VARCHAR(10) CHECK (LEN(sdt_kh) = 10) CONSTRAINT PK_KHACHHANG PRIMARY KEY,
	ten_kh NVARCHAR(50) NOT NULL,
	diem_tluy DECIMAL(15,0) CHECK (diem_tluy >= 0),
	tthai_kh BIT DEFAULT 1
);
GO 

CREATE TABLE SAN_PHAM (
	ma_sp VARCHAR(10) CONSTRAINT PK_SANPHAM PRIMARY KEY,
	ten_sp NVARCHAR(255) NOT NULL,
	gia DECIMAL(15,0) CHECK (gia > 0),
	anh IMAGE NOT NULL,
	kthuoc_sp VARCHAR(10) NOT NULL,
	sluong_sp INT CHECK (sluong_sp >= 0),
	tthai_sp BIT DEFAULT 1
);
GO

CREATE TABLE HOA_DON (
	ma_hd VARCHAR(10) CONSTRAINT PK_HOADON PRIMARY KEY,
	ngay_xuat DATE NOT NULL,
	tong_tien DECIMAL(15,0),
	giam_gia DECIMAL (15,0) NOT NULL,
	tthai_hd BIT DEFAULT 1,
	ma_nv VARCHAR(10),
	sdt_kh VARCHAR(10) CHECK (LEN(sdt_kh) = 10),
	FOREIGN KEY (ma_nv) REFERENCES NHAN_VIEN(ma_nv),
	FOREIGN KEY (sdt_kh) REFERENCES KHACH_HANG(sdt_kh)
);
GO

CREATE TABLE CHI_TIET_HOA_DON (
	ma_hd VARCHAR(10),
	ma_sp VARCHAR(10),
	sluong INT NOT NULL,
	tthai_cthd BIT DEFAULT 1,
	CONSTRAINT PK_CHITIETHD PRIMARY KEY (ma_hd, ma_sp),
	FOREIGN KEY (ma_hd) REFERENCES HOA_DON(ma_hd),
	FOREIGN KEY (ma_sp) REFERENCES SAN_PHAM(ma_sp)
);
GO

CREATE TABLE NHA_CUNG_CAP (
	ma_ncc VARCHAR(10) CONSTRAINT PK_NHACUNGCAP PRIMARY KEY,
	ten_ncc NVARCHAR(50) NOT NULL,
	sdt_ncc VARCHAR(10) CHECK (LEN(sdt_ncc) = 10) NOT NULL,
	dchi_ncc NVARCHAR(255) NOT NULL,
	tthai_ncc BIT DEFAULT 1
);
GO

CREATE TABLE LO_HANG (
	ma_lo VARCHAR(10) CONSTRAINT PK_LOHANG PRIMARY KEY,
	ma_ncc VARCHAR(10) CONSTRAINT FK_LOHANG 
		FOREIGN KEY REFERENCES NHA_CUNG_CAP(ma_ncc),
	ngay_nhap DATE NOT NULL,
	tthai_lo BIT DEFAULT 1
);
GO

CREATE TABLE CHI_TIET_LO_HANG (
	ma_lo VARCHAR(10),
	ma_sp VARCHAR(10),
	gia_nhap DECIMAL(15,0) CHECK (gia_nhap > 0),
	sluong_nhap INT CHECK (sluong_nhap > 0),
	tthai_ctlh BIT DEFAULT 1,
	CONSTRAINT PK_CHITIETLH PRIMARY KEY(ma_lo, ma_sp),
	FOREIGN KEY (ma_lo) REFERENCES LO_HANG(ma_lo),
	FOREIGN KEY (ma_sp) REFERENCES SAN_PHAM(ma_sp)
);
GO